config/routes.rb
Rails.application.routes.draw do

  root :to => 'games#index'
  #temporary root path for now

  resources :users, only:[:new, :create] do
   resources :chats, only: [:index, :show, :create]
  end

  resources :sessions, only:[:new, :destroy, :create]
    resources :messages, only:[:create]

  resources :games do
    resources :cells
  end
  resources :cells do
    resources :moves
  end
  # get '/games/new' => 'game#update2'
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/chat.rb
class Chat < ApplicationRecord
  # has_many :messages, dependent: :destroy
  # has_many :subscriptions, dependent: :destroy
  # #if chat is destroyed all messages and subscriptions will also be  destroyed
  # has_many :users, through: :subscriptions
  # validates :identifier, presence: true, uniqueness: true,    case_sensitive: false

  has_many :messages, dependent: :destroy
  has_many :subscriptions
  has_many :users, through: :subscriptions

  validates :identifier, presence: true, uniqueness: true, case_sensitive: false
end

app/controllers/chats_controller.rb
require 'securerandom'

class ChatsController < ApplicationController
  before_action :require_login
  def index
    chats = current_user.chats
    @existing_chats_users = current_user.existing_chats_users
  end
  def create
    @other_user = User.find(params[:other_user])
    @chat = find_chat(@other_user) || Chat.new(identifier: SecureRandom.hex)
    if !@chat.persisted?
      @chat.save
      @chat.subscriptions.create(user_id: current_user.id)
      @chat.subscriptions.create(user_id: @other_user.id)
    end
    redirect_to user_chat_path(current_user, @chat,  :other_user => @other_user.id)
  end
  def show
    @other_user = User.find(params[:other_user])
    @chat = Chat.find_by(id: params[:id])
    @message = Message.new
  end
  
private
  def find_chat(second_user)
    chats = current_user.chats
    chats.each do |chat|
      chat.subscriptions.each do |s|
        if s.user_id == second_user.id
          return chat
        end
      end
    end
    nil
  end
  def require_login
    redirect_to new_session_path unless logged_in?
  end
end

app/views/chats/index.html.erb
<div class="scroll-3">
  Previous Games with Users:
  <ul>
   <% if @existing_chats_users %>
     <% @existing_chats_users.each do |other_user| %>
      <% if other_user != current_user %>
        <li>
          <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
          <%= other_user.username %>
          <% end %>
        </li>
       <% end %>
     <% end %>
    <% end %>
  </ul>
</div>
<div class="scroll-3">
  Current Players Online:
  <ul>
    <% User.all.each do |other_user| %>
     <% if other_user != current_user %>
       <li>
         <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
         <%= other_user.username %>
         <% end %>
       </li>
      <% end %>
    <% end %>
  </ul>
</div>
<div class="center">
  <%= link_to "Home", games_path %>
</div>

app/views/chats/show.html.erb
<div class="scroll-2">
  <h4>Chat with <%= @other_user.username %></h4>
  <% if @chat.messages.any? %>
    <div id="messages">
      <%= render partial: 'messages/message', collection: @chat.messages.order(id: :asc)%>
    </div>
  <%else%>
    <div id="messages">
    </div>
  <%end%>
</div>
<div class="chat">
  <%= render partial: 'messages/message_form', locals: {message: @message, chat: @chat}%>
  <p><%= link_to "Back to Main Chat", user_chats_path(current_user.id) %></p>

</div>

<script>
  createMessageChannel();
  messageForm();
  //defaults scrolling to bottom
  $(".scroll").scrollTop($(".scroll")[0].scrollHeight);
</script>