config/routes.rb
Rails.application.routes.draw do

  root :to => 'games#index'
  #temporary root path for now

  resources :users, only:[:new, :create] do
   resources :chats, only: [:index, :show, :create]
  end

  resources :sessions, only:[:new, :destroy, :create]
    resources :messages, only:[:create]

  resources :games do
    resources :cells
  end
  resources :cells do
    resources :moves
  end
  # get '/games/new' => 'game#update2'
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :cells
  def create_game(p1_name, p2_name)
    self.update({:player_1_name => p1_name, :player_2_name => p2_name})


  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    render :home
  end

  def new
    @number = []
    Move.delete_all
    Cell.delete_all
    @game = Game.create
    Cell.create_grid(@game.id)
    @moves = Move.all
    @cells = Cell.all.order(:player,:x,:y)
    @player_id = 1

  end
  def create
    # @game.create_game
  end

  def update

    @cells = Cell.all.order(:id,:player,:x,:y,:hit)
    @game = Game.find(params[:id].to_i)
    @cell = Cell.find(params[:cell].fetch(:cell_id).to_i)
    @cell_left = Cell.where(x:(@cell.x - 1))
    @cell.update({:ship => params[:cell].fetch(:ship)})
    @player_id = 1
    @number = Cell.where(player:1, ship:true)
    render :new
  end
end

app/views/games/home.html.erb
<div class="jumbotron4">
  <div class="container text-center">
    <h1>Battleship!</h1>
    <br>
    <% if current_user %>
      Previous Games with Users:
      <ul>
       <% if @existing_chats_users %>
         <% @existing_chats_users.each do |other_user| %>
          <% if other_user != current_user %>
            <li>
              <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
              <%= other_user.username %>
              <% end %>
            </li>
           <% end %>
         <% end %>
        <% end %>
      </ul>
      Current Players Online:
      <div class="scroll">
          <% User.all.each do |other_user| %>
            <% if other_user != current_user %>
            <p>
              <%= link_to(user_chats_path(current_user, :other_user => other_user.id), method: :post) do %>
              <%= other_user.username %>
              <% end %>
            </p>
            <% end %>
          <% end %>
      </div>
    <% end %>
    <% if current_user %>
      <form action="/games/new" method="get">
        <button type="submit" name="button">New game</button>
      </form>
    <% else %>
      <p>Please log in or sign up to play battlship, if you dare...</p>
    <% end %>
  </div>
</div>

app/views/games/index.html.erb
<h1></h1>
<%= @cells %>
It is turn of <b>Player <%=@player_id%></b>

<% @cells.each do |cell| %>
  <% if @player_id == 1 %>
    <%= form_for [cell] do |t| %>
      <% if cell.player == 2 %>
        Cell has ship? <%=cell.ship%>
        | Player <%=cell.player %>
        | x: <%=cell.x%>
        | y: <%=cell.y%>
        | Cell has been hit ? <%=cell.hit%>
        <%= t.submit %>
      <% end %>
    <% end %>
  <% else %>
    <%= form_for [cell] do |t| %>
      <% if cell.player == 1 %>
        Cell has ship? <%=cell.ship%>
        | Player <%=cell.player %>
        | x: <%=cell.x%>
        | y: <%=cell.y%>
        | Cell has been hit ? <%=cell.hit%>
        <%= t.submit %>
      <% end %>
    <% end %>
  <% end %>
  <% else %>
<% end %>

<%@moves.each do |move|%>
  Player <%=move.player_id %>, x <%=move.x%>, y <%=move.y%>, hit? <%=move.hit%> <br>
<%end%>
<!--
<body>
  <div class="container row">
<div class="col-10">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">A</th>
          <th scope="col">B</th>
          <th scope="col">C</th>
        </tr>
      </thead>
      <form method="post">
        <tbody>
          <tr>
            <th class="row-dark" scope="row">1</th>
            <td><div id="11"><input type="button" class="form-control" value="1100"></div></td>
            <td><div id="12"><input type="button" class="form-control" value="1200"></div></td>
            <td><div id="13"><input type="button" class="form-control" value="1300"></div></td>
          </tr>
          <tr>
            <th class="row-dark" scope="row">2</th>
            <td><div id="21"><input type="button" class="form-control" value="2100"></div></td>
            <td><div id="22"><input type="button" class="form-control" value="2200"></div></td>
            <td><div id="23"><input type="button" class="form-control" value="2300"></div></td>
          </tr>
          <tr>
            <th class="row-dark" scope="row">3</th>
            <td><div id="31"><input type="button" class="form-control" value="3100"></div></td>
            <td><div id="32"><input type="button" class="form-control" value="3200"></div></td>
            <td><div id="33"><input type="button" class="form-control" value="3300"></div></td>
          </tr>
        </tbody>
      </form>
    </table>
  </div>

</div>
<input type="submit" class="button" value="Submit">

</body>
</html> -->

app/views/games/new.backup.html.erb
<div class="jumbotron jumbotron1">
  <h1>New Game</h1><br>
  <%= form_for @game, :url => game_cells_path(@game.id), :method => "get" do |f| %>
  <% f.hidden_field :game_id, :value => @game.id %>
  <%= f.label "Player 1 name:" %>
  <%= f.text_field :player_1_name %>
  <%= f.label "Player 2 name:" %>
  <%= f.text_field :player_2_name %>
  <%= f.submit %>
  <% end %>

  <hr>
</div>
<div class="jumbotron jumbotron2">
  <% if @player_id == 1 %>
  <div class="container battleship">
    <div class="row-12">
      <div class="col-4">
        <h4>PLAYER 1 place your ships:</h4>
        <table class="table">
          <% data_x = 1 %>
          <% data_y = 1 %>
          <thead >
            <tr>
              <% letters = '@' %>
              <th scope="col">X</th>
              <% 10.times do %>
              <th scope="col"><%=letters.next!%></th>
              <%end%>
            </tr>
          </thead>
          <% 10.times do %>
          <tr>
            <th class="row-dark" scope="row">
              <%= data_y %>
            </th>
            <% 10.times do %>

            <td><% player_cells = @cells.select{|element| element.player == 1}.select{|element| element.y == data_y}.select{|element| element.x == data_x} %>
              <%= form_for player_cells, :url => game_path(@game.id), :method => "patch" do |t| %>
              <%= t.hidden_field :cell_id, :value => player_cells[0].id %>

              <% if player_cells[0].ship %>
                <%= t.hidden_field :ship, :value => false %>

              <% else %>
                <%= t.hidden_field :ship, :value => true %>
              <% end %>

                <%= t.submit "", :class => "ship_place" %>
              <% end %>
            </td>

            <% data_x += 1 %>
            <%end%>
            <% data_x = 1 %>
            <% data_y += 1 %>
          </tr>
          <%end%>
        </table>
      </div>
    </div>
  </div>
  <%end%>

app/views/games/new.html.erb
<div class="jumbotron jumbotron1">
  <h1>New Game</h1><br>
  <div class="center">
    <% if @number.length >= 7 %>
      <%= form_for @game, :url => game_cells_path(@game.id), :method => "get" do |f| %>
      <% f.hidden_field :game_id, :value => @game.id %>
      <%= f.submit "Start!" %>
      <% end %>
    <%end%>
  </div>


  <hr>
</div>
<% if @number.length < 7 %> <!-- Player ships allowed -->
<div class="jumbotron jumbotron2">
  <% if @player_id == 1 %>
  <div class="container battleship_placement">
    <div class="row">
    <div class="col-4">
    </div>
      <div class="col-4">
        <h4>PLAYER 1 place your ships:</h4>
        <table class="table table-2">
          <% data_x = 1 %>
          <% data_y = 1 %>
          <thead >
            <tr>
              <% letters = '@' %>
              <th scope="col">X</th>
              <% 5.times do %> <!-- To change gameboard size -->
              <th scope="col"><%=letters.next!%></th>
              <%end%>
            </tr>
          </thead>
          <% 5.times do %> <!-- To change gameboard size -->
          <tr>
            <th class="row-dark" scope="row">
              <%= data_y %>
            </th>
            <% 5.times do %> <!-- To change gameboard size -->

            <td><% player_cells = @cells.select{|element| element.player == 1}.select{|element| element.y == data_y}.select{|element| element.x == data_x} %>
              <% if player_cells[0].ship %>
              <!-- IF SHIP IS PRESENT -->
              <%= form_for player_cells, :url => game_path(@game.id), :method => "patch" do |t| %>
              <%= t.hidden_field :cell_id, :value => player_cells[0].id %>

              <% if player_cells[0].ship %>
              <%= t.hidden_field :ship, :value => false %>
              <% else %>
              <%= t.hidden_field :ship, :value => true %>
              <% end %>

              <%= image_submit_tag "SHIP.png", :id => "submit" %>
              <% end %>
              <!-- IF SHIP IS PRESENT -->
              <%else%>
              <!-- IF SHIP IS NOT PRESENT -->
              <%= form_for player_cells, :url => game_path(@game.id), :method => "patch" do |t| %>
              <%= t.hidden_field :cell_id, :value => player_cells[0].id %>

              <% if player_cells[0].ship %>
              <%= t.hidden_field :ship, :value => false %>
              <% else %>
              <%= t.hidden_field :ship, :value => true %>
              <% end %>

              <%= image_submit_tag "OPENWATER.png", :id => "submit" %>
              <% end %>
              <!-- IF SHIP IS NOT PRESENT -->
              <%end%>
            </td>
    <% else %>
            <% data_x += 1 %>
            <%end%>
            <% data_x = 1 %>
            <% data_y += 1 %>
          </tr>
          <%end%>
        </table>
      </div>
      <div class="col-4">
      </div>
    </div>
  <%end%>
</div>
<% end %>
</div>

<!--
  <div class="chat_window">
    <iframe src = "/" width = "500" height = "500">
      Sorry your browser does not support inline frames.
    </iframe>
  </div> -->