config/routes.rb
Rails.application.routes.draw do

  root :to => 'games#index'
  #temporary root path for now

  resources :users, only:[:new, :create] do
   resources :chats, only: [:index, :show, :create]
  end

  resources :sessions, only:[:new, :destroy, :create]
    resources :messages, only:[:create]

  resources :games do
    resources :cells
  end
  resources :cells do
    resources :moves
  end
  # get '/games/new' => 'game#update2'
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/views/layouts/_form.html.erb
<%= render "layouts/errors", :object => @grid %>

<%= form_for @grid do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="css/styles.css">
    <link href='https://fonts.googleapis.com/css?family=Pirata One' rel='stylesheet'>
    <meta charset="utf-8">
    <title>Battleship</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar  navbar-light" style="background-color: #141313;">
      <div class="navbar-class">
        <% if current_user %>
        Logged in as <%= current_user.username %>.
        <%= link_to "Logout", session_path(current_user.id), method: :delete  %>
        <% else %>
        <%= link_to "Sign Up", new_user_path %> |
        <%= link_to "Log In", new_session_path %>
        <% end %>
        <p id=”notice”><%= notice %></p>
      </div>
    </header>
    <%= yield %>
  </body>
</html>